In [1]:
pip install mlflow

Collecting mlflow
  Downloading mlflow-3.10.1-py3-none-any.whl.metadata (31 kB)
Collecting mlflow-skinny==3.10.1 (from mlflow)
  Downloading mlflow_skinny-3.10.1-py3-none-any.whl.metadata (32 kB)
Collecting mlflow-tracing==3.10.1 (from mlflow)
  Downloading mlflow_tracing-3.10.1-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Using cached flask_cors-6.0.2-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: Flask<4 in c:\users\danch\anaconda3\lib\site-packages (from mlflow) (3.0.3)
Requirement already satisfied: alembic!=1.10.0,<2 in c:\users\danch\anaconda3\lib\site-packages (from mlflow) (1.13.3)
Requirement already satisfied: cryptography<47,>=43.0.0 in c:\users\danch\anaconda3\lib\site-packages (from mlflow) (43.0.0)
Collecting docker<8,>=4.0.0 (from mlflow)
  Using cached docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Using cached graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting huey<3,>=2.5.4 (from mlflow)
  Using cached huey-2.6.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: matplotlib<4 in c:\users\danch\anaconda3\lib\site-packages (from mlflow) (3.9.2)
Requirement already satisfied: numpy<3 in c:\users\danch\anaconda3\lib\site-packages (from mlflow) (1.26.4)
Requirement already satisfied: pandas<3 in c:\users\danch\anaconda3\lib\site-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<24,>=4.0.0 in c:\users\danch\anaconda3\lib\site-packages (from mlflow) (16.1.0)
Requirement already satisfied: scikit-learn<2 in c:\users\danch\anaconda3\lib\site-packages (from mlflow) (1.5.1)
Requirement already satisfied: scipy<2 in c:\users\danch\anaconda3\lib\site-packages (from mlflow) (1.13.1)
Collecting skops<1 (from mlflow)
  Downloading skops-0.13.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\users\danch\anaconda3\lib\site-packages (from mlflow) (2.0.34)
Collecting waitress<4 (from mlflow)
  Using cached waitress-3.0.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: cachetools<8,>=5.0.0 in c:\users\danch\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in c:\users\danch\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (8.1.7)
Requirement already satisfied: cloudpickle<4 in c:\users\danch\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (3.0.0)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading databricks_sdk-0.102.0-py3-none-any.whl.metadata (40 kB)
Collecting fastapi<1 (from mlflow-skinny==3.10.1->mlflow)
  Downloading fastapi-0.135.1-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: gitpython<4,>=3.1.9 in c:\users\danch\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (3.1.43)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in c:\users\danch\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (7.0.1)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading opentelemetry_api-1.40.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading opentelemetry_proto-1.40.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: packaging<27 in c:\users\danch\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (24.1)
Requirement already satisfied: protobuf<7,>=3.12.0 in c:\users\danch\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (4.25.3)
Requirement already satisfied: pydantic<3,>=2.0.0 in c:\users\danch\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (2.8.2)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in c:\users\danch\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (0.21.0)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\danch\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (6.0.1)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\danch\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (2.32.3)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.10.1->mlflow)
  Using cached sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\danch\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (4.11.0)
Collecting uvicorn<1 (from mlflow-skinny==3.10.1->mlflow)
  Downloading uvicorn-0.42.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: Mako in c:\users\danch\anaconda3\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.2.3)
Requirement already satisfied: cffi>=1.12 in c:\users\danch\anaconda3\lib\site-packages (from cryptography<47,>=43.0.0->mlflow) (1.17.1)
Requirement already satisfied: pywin32>=304 in c:\users\danch\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (305.1)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\danch\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.2.3)
Requirement already satisfied: Werkzeug>=3.0.0 in c:\users\danch\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\danch\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\danch\anaconda3\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: blinker>=1.6.2 in c:\users\danch\anaconda3\lib\site-packages (from Flask<4->mlflow) (1.6.2)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.8-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Using cached graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\danch\anaconda3\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\danch\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\danch\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\danch\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\danch\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.4.4)
Requirement already satisfied: pillow>=8 in c:\users\danch\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\danch\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (3.1.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\danch\anaconda3\lib\site-packages (from pandas<3->mlflow) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\danch\anaconda3\lib\site-packages (from pandas<3->mlflow) (2023.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\danch\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\danch\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (3.5.0)
Collecting prettytable>=3.9 (from skops<1->mlflow)
  Using cached prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\danch\anaconda3\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.0.1)
Requirement already satisfied: pycparser in c:\users\danch\anaconda3\lib\site-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (2.21)
Requirement already satisfied: colorama in c:\users\danch\anaconda3\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.10.1->mlflow) (0.4.6)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow)
  Downloading google_auth-2.49.1-py3-none-any.whl.metadata (6.2 kB)
Collecting protobuf<7,>=3.12.0 (from mlflow-skinny==3.10.1->mlflow)
  Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting starlette>=0.46.0 (from fastapi<1->mlflow-skinny==3.10.1->mlflow)
  Using cached starlette-0.52.1-py3-none-any.whl.metadata (6.3 kB)
Collecting typing-inspection>=0.4.2 (from fastapi<1->mlflow-skinny==3.10.1->mlflow)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting annotated-doc>=0.0.2 (from fastapi<1->mlflow-skinny==3.10.1->mlflow)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\danch\anaconda3\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (4.0.7)
Requirement already satisfied: zipp>=0.5 in c:\users\danch\anaconda3\lib\site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.10.1->mlflow) (3.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\danch\anaconda3\lib\site-packages (from Jinja2>=3.1.2->Flask<4->mlflow) (2.1.3)
Collecting opentelemetry-semantic-conventions==0.61b0 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.10.1->mlflow)
  Downloading opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: wcwidth in c:\users\danch\anaconda3\lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.2.5)
Requirement already satisfied: annotated-types>=0.4.0 in c:\users\danch\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (0.6.0)
Requirement already satisfied: pydantic-core==2.20.1 in c:\users\danch\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (2.20.1)
Requirement already satisfied: six>=1.5 in c:\users\danch\anaconda3\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\danch\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\danch\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\danch\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (2025.8.3)
Requirement already satisfied: h11>=0.8 in c:\users\danch\anaconda3\lib\site-packages (from uvicorn<1->mlflow-skinny==3.10.1->mlflow) (0.14.0)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\danch\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (4.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\danch\anaconda3\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (0.2.8)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\danch\anaconda3\lib\site-packages (from starlette>=0.46.0->fastapi<1->mlflow-skinny==3.10.1->mlflow) (4.2.0)
Collecting typing-extensions<5,>=4.0.0 (from mlflow-skinny==3.10.1->mlflow)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: sniffio>=1.1 in c:\users\danch\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi<1->mlflow-skinny==3.10.1->mlflow) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\danch\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (0.4.8)
Downloading mlflow-3.10.1-py3-none-any.whl (10.2 MB)
   ---------------------------------------- 0.0/10.2 MB ? eta -:--:--
   ------- -------------------------------- 1.8/10.2 MB 14.3 MB/s eta 0:00:01
   ---------------------------------------  10.0/10.2 MB 38.8 MB/s eta 0:00:01
   ---------------------------------------- 10.2/10.2 MB 28.8 MB/s eta 0:00:00
Downloading mlflow_skinny-3.10.1-py3-none-any.whl (3.0 MB)
   ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
   ---------------------------------------- 3.0/3.0 MB 14.5 MB/s eta 0:00:00
Downloading mlflow_tracing-3.10.1-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 1.5/1.5 MB 38.5 MB/s eta 0:00:00
Using cached docker-7.1.0-py3-none-any.whl (147 kB)
Using cached flask_cors-6.0.2-py3-none-any.whl (13 kB)
Using cached graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Using cached huey-2.6.0-py3-none-any.whl (76 kB)
Downloading skops-0.13.0-py3-none-any.whl (131 kB)
Using cached waitress-3.0.2-py3-none-any.whl (56 kB)
Downloading databricks_sdk-0.102.0-py3-none-any.whl (838 kB)
   ---------------------------------------- 0.0/838.5 kB ? eta -:--:--
   --------------------------------------- 838.5/838.5 kB 36.0 MB/s eta 0:00:00
Downloading fastapi-0.135.1-py3-none-any.whl (116 kB)
Downloading graphql_core-3.2.8-py3-none-any.whl (207 kB)
Using cached graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading opentelemetry_api-1.40.0-py3-none-any.whl (68 kB)
Downloading opentelemetry_proto-1.40.0-py3-none-any.whl (72 kB)
Downloading opentelemetry_sdk-1.40.0-py3-none-any.whl (141 kB)
Downloading opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl (231 kB)
Using cached prettytable-3.17.0-py3-none-any.whl (34 kB)
Downloading protobuf-6.33.6-cp310-abi3-win_amd64.whl (437 kB)
Using cached sqlparse-0.5.5-py3-none-any.whl (46 kB)
Downloading uvicorn-0.42.0-py3-none-any.whl (68 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading google_auth-2.49.1-py3-none-any.whl (240 kB)
Using cached starlette-0.52.1-py3-none-any.whl (74 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: huey, waitress, typing-extensions, sqlparse, protobuf, prettytable, graphql-core, annotated-doc, uvicorn, typing-inspection, starlette, opentelemetry-proto, opentelemetry-api, graphql-relay, docker, skops, opentelemetry-semantic-conventions, graphene, google-auth, Flask-CORS, opentelemetry-sdk, fastapi, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.11.0
    Uninstalling typing_extensions-4.11.0:
      Successfully uninstalled typing_extensions-4.11.0
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.3
    Uninstalling protobuf-4.25.3:
      Successfully uninstalled protobuf-4.25.3
Successfully installed Flask-CORS-6.0.2 annotated-doc-0.0.4 databricks-sdk-0.102.0 docker-7.1.0 fastapi-0.135.1 google-auth-2.49.1 graphene-3.4.3 graphql-core-3.2.8 graphql-relay-3.2.0 huey-2.6.0 mlflow-3.10.1 mlflow-skinny-3.10.1 mlflow-tracing-3.10.1 opentelemetry-api-1.40.0 opentelemetry-proto-1.40.0 opentelemetry-sdk-1.40.0 opentelemetry-semantic-conventions-0.61b0 prettytable-3.17.0 protobuf-6.33.6 skops-0.13.0 sqlparse-0.5.5 starlette-0.52.1 typing-extensions-4.15.0 typing-inspection-0.4.2 uvicorn-0.42.0 waitress-3.0.2
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.37.1 requires protobuf<6,>=3.20, but you have protobuf 6.33.6 which is incompatible.

In [3]:
import mlflow

In [4]:
import pandas as pd

In [41]:
test_df = pd.read_csv(r"C:\Users\Danch\PycharmProjects\Credit_Scoring_Model_w_transformers\data\Give_risks\test_give_me_credit_baseline.csv")

test_df.head(5)

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,MonthlyIncome_missing,NumberOfDependents_missing,HasHiddenLatePayments,TotalLatePayments_weighted
0,0,NaN,0.885519,43,0.0,0.177513,5700.0,4,0.0,0,0.0,0.0,0,0,0,0.0
1,1,NaN,0.463295,57,0.0,0.527237,9141.0,15,0.0,4,0.0,2.0,0,0,0,0.0
2,2,NaN,0.043275,59,0.0,0.687648,5083.0,12,0.0,1,0.0,2.0,0,0,0,0.0
3,3,NaN,0.280308,38,1.0,0.925961,3200.0,7,0.0,2,0.0,0.0,0,0,0,1.0
4,4,NaN,1.000000,27,0.0,0.019917,3865.0,4,0.0,0,0.0,1.0,0,0,0,0.0

In [54]:
index = test_df["Unnamed: 0"] + 1

In [55]:
drop_cols = ["SeriousDlqin2yrs"]

In [56]:
X_test = test_df.drop(columns=drop_cols, errors='ignore')

In [57]:
model = mlflow.sklearn.load_model(r"C:\Users\Danch\PycharmProjects\Credit_Scoring_Model_w_transformers\mlartifacts\0\models\m-44a30fe0f5614878ac1bb34dd1f568d1\artifacts")

C:\Users\Danch\anaconda3\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.7.2 when using version 1.5.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\Danch\anaconda3\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 1.7.2 when using version 1.5.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\Danch\anaconda3\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.7.2 when using version 1.5.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\Danch\anaconda3\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator ColumnTransformer from version 1.7.2 when using version 1.5.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\Danch\anaconda3\Lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator Pipeline from version 1.7.2 when using version 1.5.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [58]:
model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(force_int_remainder_cols='deprecated',
                                   transformers=[('num', StandardScaler(),
                                                  Index(['Unnamed: 0', 'RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents', 'MonthlyIncome_missing',
       'NumberOfDependents_missing', 'HasHiddenLatePayments',
       'TotalLatePayments_weighted'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index([], dtype='object'))])),
                ('ensemble',
                 <catboost.core.CatBoostClassifier object at 0x000001EF0EB62960>)])

In [59]:
probs = model.predict_proba(X_test)[:, 1]

In [60]:
# probs = model.predict(X_test)

In [61]:
result = pd.DataFrame({"Id":index, "Probability": probs})
len(result)

101503

In [62]:
result.head(10)

   Id  Probability
0   1     0.237806
1   2     0.211684
2   3     0.198592
3   4     0.211393
4   5     0.247557
5   6     0.211695
6   7     0.221589
7   8     0.205617
8   9     0.193065
9  10     0.290984

In [63]:
result.to_csv("test_output_prob.csv", index=False)

In [64]:
# result.to_csv("test_output_bin.csv", index=False)

In [65]:
result["Id"]

0              1
1              2
2              3
3              4
4              5
           ...
101498    101499
101499    101500
101500    101501
101501    101502
101502    101503
Name: Id, Length: 101503, dtype: int64